### ISSUE TITLE
Streaming Section looks funky

### ISSUE THREAD

**Issue by tdrayson** [matthewbrandt/mattytwo.shoes#14]
<img width="949" alt="Screenshot 2021-11-27 at 11 53 40" src="https://user-images.githubusercontent.com/33532995/143680219-039d9187-bbdf-41f4-b311-85a97442bd70.png">

**Comment by matthewbrandt** [comment]
browser / OS? that's weird

**Comment by tdrayson** [comment]
Device: MacBook Pro M1 
OS: macOS Monterey
Browser: Firefox Developer Edition

**Comment by matthewbrandt** [comment]
@tdrayson is this still the case?

**Comment by tdrayson** [comment]
Looks to be fixed
