### ISSUE TITLE
highlight text should be lighter/white

### ISSUE THREAD

**Issue by matthewbrandt** [matthewbrandt/mattytwo.shoes#2]
this is what i tried and it wasn't working
```
.lights-off::selection { color: #fff; } 
.lights-off::-moz-selection { color: #fff; }
```

**Comment by tdrayson** [comment]
Try adding this

`::selection {
	color: #fff;
	background: #5763d8;
}
::-moz-selection {
	color: #fff;
	background: #5763d8;
}`

**Comment by matthewbrandt** [comment]
tried doing that and setting it in various places but it still doesn't work well. need to do this on rebuild probably...
