### ISSUE TITLE
Title “below” graphic on Mobile.

### ISSUE THREAD

**Issue by exegeteio** [matthewbrandt/mattytwo.shoes#4]
Using Firefox Focus, on iOS, on an iPhone XS, the header appears "below@ the bubble graphic.  

![image](https://user-images.githubusercontent.com/2538668/129455561-d0fa6ce9-2342-491d-9db8-25d60a5b7bdb.jpeg)

**Comment by matthewbrandt** [comment]
should be fixed in https://github.com/matthewbrandt/mattytwo.shoes/commit/ffe89e7f07e1b5641143d7378059cdf9b50bfd98
@exegeteio if you get the chance to retest that would be cool, i don't see it anymore (i was able to replicate on mobile chrome)

**Comment by exegeteio** [comment]
@matthewbrandt I no longer see the bubble graphic at all.  Is that intentional?

![image](https://user-images.githubusercontent.com/2538668/129480019-57e8ffe5-03f3-4b11-8ec4-2f7b16bfc6e9.png)

**Comment by matthewbrandt** [comment]
yeah it shows below with my picture :)
